"""Initial migration

Revision ID: df83fd21db4f
Revises: 
Create Date: 2024-02-07 18:15:46.491395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df83fd21db4f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('imdb_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('rated', sa.String(), nullable=True),
    sa.Column('released', sa.String(), nullable=True),
    sa.Column('runtime', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('director', sa.String(), nullable=True),
    sa.Column('writer', sa.String(), nullable=True),
    sa.Column('actors', sa.String(), nullable=True),
    sa.Column('plot', sa.Text(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('awards', sa.String(), nullable=True),
    sa.Column('poster', sa.String(), nullable=True),
    sa.Column('ratings', sa.JSON(), nullable=True),
    sa.Column('metascore', sa.String(), nullable=True),
    sa.Column('imdb_rating', sa.String(), nullable=True),
    sa.Column('imdb_votes', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('dvd', sa.String(), nullable=True),
    sa.Column('box_office', sa.String(), nullable=True),
    sa.Column('production', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('response', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('imdb_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    # ### end Alembic commands ###
